logging:
    level:
        org.springframework.security: trace
spring:
  application:
      name: ${SPRING_APPLICATION_NAME:auth-service}
server:
    port: ${PORT:9000}

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_CLIENT_SERVICE:eureka-service}:${EUREKA_SERVER_PORT:8761}/eureka/
    instance:
        prefer-ip-address: true