spring:
    application:
        name: user-service

    data:
        mongodb:
            uri: mongodb://root:root@localhost:27017/
            database: user_service
            auto-index-creation: true

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://127.0.0.01:9000"

server:
    port: 8001

eureka:
    client:
        service-url:
            defaultZone: http://eureka-service:8761/eureka/
    instance:
        prefer-ip-address: true