spring:
    application:
        name: ${SPRING_APPLICATION_NAME:eureka-service}

server:
    port: ${PORT:8761}

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
